color_names:
  - red
  - green
  - blue
  - yellow
  - orange
  - purple
  - pink
  - cyan
  - brown
  - black
  - white
  - gray
  - silver
  - gold
  - violet
  - indigo
  - maroon
  - olive
  - lime
  - teal
  - navy
  - fuchsia
  - aqua
  - beige
  - coral
  - khaki
  - lavender
  - magenta
  - plum
  - turquoise
  - salmon
  - tomato
  - tan
  - wheat
  - orchid
  - peru
  - thistle
  - rosybrown
  - slategray
  - darkorange
  - forestgreen
  - royalblue
  - darkviolet
  - saddlebrown
  - darkseagreen
  - mediumorchid
  - firebrick
  - mediumseagreen
  - cadetblue
  - chocolate
  - indianred
  - darkslategray
  - dodgerblue
  - deeppink
  - darkkhaki
  - lightcoral
  - darkolivegreen
  - mediumpurple
  - sienna
  - darkcyan
  - olivedrab
  - blueviolet
  - slateblue
  - lightseagreen
  - steelblue
  - palevioletred
  - darkmagenta
  - darkgoldenrod
  - rosybrown
  - dimgray
  - palegreen
  - peru
  - mediumblue
  - midnightblue
  - darksalmon
  - darkred
  - darkslateblue
  - darkturquoise
  - darkgreen
  - darkorchid
  - darkslategray
  - darkblue
  - darkcyan
  - darkorange
  - darkkhaki
  - darkseagreen
  - darkolivegreen
  - darkorchid
  - darkviolet
  - darkred
  - darksalmon
  - darkslateblue
  - darkslategray
  - darkturquoise
  - darkviolet
  - deeppink
  - dimgray
  - dodgerblue
  - firebrick
  - forestgreen
  - gold
  - gray
  - green
  - indianred
  - indigo
  - khaki
  - lavender
  - lime
  - magenta
  - maroon
  - mediumorchid
  - mediumpurple
  - midnightblue
  - navy
  - olive
  - olivedrab
  - orange
  - orchid
  - palegreen
  - palevioletred
  - peru
  - pink
  - plum
  - purple
  - red
  - rosybrown
  - royalblue
  - saddlebrown
  - salmon
  - sienna
  - slateblue
  - slategray
  - teal
  - thistle
  - tomato
  - turquoise
  - violet
  - wheat
  - white
